### PR TITLE
Feature/grid 204: Group View Prototype

### PR DESCRIPTION
**Pull request by Dwaynekj**

### CODE REVIEW

**Comment by Dwaynekj** [comment]
@joneit Paired PR with https://github.com/openfin/fin-hypergrid/pull/207

**Comment by Dwaynekj** [comment]
@joneit Ready

**Comment by joneit** [comment]
@Dwayne As part of this PR please bump version in `package.json` to `0.11.6`. (FYI, version `0.11.5` is tree sorting.) Thx.

**Comment by Dwaynekj** [comment]
@joneit Ready

**Comment by Dwaynekj** [comment]
@joneit Ready once more

**Comment by dwayne** [comment]
Oh, that's how I got roped into this conversation. @joneit You used the wrong handle.

**Pull request merged**
